# coding: utf-8

"""
    Сервис баннеров

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.banner_get200_response_inner import BannerGet200ResponseInner

class TestBannerGet200ResponseInner(unittest.TestCase):
    """BannerGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BannerGet200ResponseInner:
        """Test BannerGet200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BannerGet200ResponseInner`
        """
        model = BannerGet200ResponseInner()
        if include_optional:
            return BannerGet200ResponseInner(
                banner_id = 56,
                tag_ids = [
                    56
                    ],
                feature_id = 56,
                content = {"title": "some_title", "text": "some_text", "url": "some_url"},
                is_active = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return BannerGet200ResponseInner(
        )
        """

    def testBannerGet200ResponseInner(self):
        """Test BannerGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
