# coding: utf-8

# flake8: noqa
"""
    Сервис баннеров

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.banner_get200_response_inner import BannerGet200ResponseInner
from openapi_client.models.banner_id_patch_request import BannerIdPatchRequest
from openapi_client.models.banner_post201_response import BannerPost201Response
from openapi_client.models.banner_post_request import BannerPostRequest
from openapi_client.models.user_banner_get400_response import UserBannerGet400Response
